# Generated by Django 3.2.6 on 2023-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='medicos',
        ),
    ]
